name: secrets workflow

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use secrets in workflow
      run: |
        echo "The secret key is ${{ secrets.TEST_SECRET }}"