# Using secrets in GitHub Actions workflow
name: secrets workflow

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use secrets in workflow
      run: |
        echo "The secret key is ${{ secrets.TEST_SECRET }}"

# using secrets as environment variables
    - name: Use secrets as env variables
      run: |
        echo "The secret is $TEST_SECRET"
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
    